### Kelvin Ndungu Wainaina
### N11/03/0589/018
### CAT 

In [1]:
# Install packages
!pip install pandas
!pip install numpy
!pip install sklearn
!pip install scikit-learn
!pip install nltk

Defaulting to user installation because normal site-packages is not writeable
Defaulting to user installation because normal site-packages is not writeable
Defaulting to user installation because normal site-packages is not writeable
Defaulting to user installation because normal site-packages is not writeable
Defaulting to user installation because normal site-packages is not writeable


In [16]:
# Imports
import pandas as pd
import numpy as np
import seaborn as sns
import nltk
import itertools
import csv
import string
import operator
import re

In [18]:
# Machine learing libraries 

from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [4]:
# Load the data
source_1 = pd.read_csv('../data/cat.csv')
source_1

Index  Country   Age   Salary Purchased
0      0    India  38.0  68000.0        No
1      1   France  43.0  45000.0       Yes
2      2  Germany  30.0  54000.0        No
3      3   France  48.0  65000.0        No
4      4  Germany  40.0      NaN       Yes
5      5    India  35.0  58000.0       Yes
6      6  Germany   NaN  53000.0        No
7      7   France  49.0  79000.0       Yes
8      8    India  50.0  88000.0        No
9      9   France  37.0  77000.0       Yes

In [5]:
#interpret each of the column
source_1.dtypes

Index          int64
Country       object
Age          float64
Salary       float64
Purchased     object
dtype: object

In [6]:
# summary of a DataFrame
source_1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   Index      10 non-null     int64  
 1   Country    10 non-null     object 
 2   Age        9 non-null      float64
 3   Salary     9 non-null      float64
 4   Purchased  10 non-null     object 
dtypes: float64(2), int64(1), object(2)
memory usage: 528.0+ bytes


In [15]:
dependent_variables = source_1.Age
independent_variabble = source_1.Country

Assumptions take in place for missing data it is the average of each category to get the missing data

In [9]:
# Mean of Ages
mean_age = np.mean(source_1.Age)
mean_age

41.111111111111114

In [10]:
# Mean of Salary
mean_salary = np.mean(source_1.Salary)
mean_salary

65222.22222222222

In [11]:
# Formatting the Data
mean_age = int(mean_age)
mean_salary = int(mean_salary)

In [12]:
# Customizing the data and patching it
source_1['Age'].fillna(value = mean_age,inplace = True)

In [13]:
# Customizing the data and patching it
source_1['Salary'].fillna(value = mean_salary,inplace = True)

In [14]:
# Load new data
source_1

Index  Country   Age   Salary Purchased
0      0    India  38.0  68000.0        No
1      1   France  43.0  45000.0       Yes
2      2  Germany  30.0  54000.0        No
3      3   France  48.0  65000.0        No
4      4  Germany  40.0  65222.0       Yes
5      5    India  35.0  58000.0       Yes
6      6  Germany  41.0  53000.0        No
7      7   France  49.0  79000.0       Yes
8      8    India  50.0  88000.0        No
9      9   France  37.0  77000.0       Yes

Meaning of the term Sentimental Analysis as per Naive Bayes Algorithm
-  Sentiment analysis is the process of classifing data in text format to detect or get insights if the data is postive , negative or neutral. It is a contextual insights of word or text from customers or users of a system or social media posts that indicate social sentiment. It help bussiness ,organization and gorvernment on products ,solution and requirements that people want or would like to have or give feedback to certain change or need.

 Machine Learning techniques
 
    1.Supervised Machine Learning

        -This

    2. Unsupervised Machine Learning 

        -This

    3. Reinforced Machine Learning

        -This

A 4-input neuron has weights 1 2 3 4 . The transfer function is Linear with a constant of proportionnality of 2
,the inputs are , 4 ,10, 5, and 20 . calcualate the output.


In [17]:

def function_neuron(weight,input_list):
    transfer_function = 2
    
    a, b, c, d = map(operator.mul, weight, input_list)
    
    output = (np.sum([a,b,c,d]) * transfer_function)
    
    return output

    
    

function_neuron([1,2,3,4],[4,10,5,20])

238

Write a program in python that will help the agency achive the following:

    -determing the salary of an employee after several years of expirience

In [20]:

# Load the data
source_2 = pd.read_csv('../data/Salary_Data.csv')
source_2

YearsExperience   Age  Salary
0               1.1  21.0   39343
1               1.3  21.5   46205
2               1.5  21.7   37731
3               2.0  22.0   43525
4               2.2  22.2   39891
5               2.9  23.0   56642
6               3.0  23.0   60150
7               3.2  23.3   54445
8               3.2  23.3   64445
9               3.7  23.6   57189
10              3.9  23.9   63218
11              4.0  24.0   55794
12              4.0  24.0   56957
13              4.1  24.0   57081
14              4.5  25.0   61111
15              4.9  25.0   67938
16              5.1  26.0   66029
17              5.3  27.0   83088
18              5.9  28.0   81363
19              6.0  29.0   93940
20              6.8  30.0   91738
21              7.1  30.0   98273
22              7.9  31.0  101302
23              8.2  32.0  113812
24              8.7  33.0  109431
25              9.0  34.0  105582
26              9.5  35.0  116969
27              9.6  36.0  112635
28             10.3  37.0  122391
29             10.5  38.0  121872

In [49]:
dependent = source_2.YearsExperience 
independent = source_2.Salary

In [50]:
dependent, independent

(0      1.1
 1      1.3
 2      1.5
 3      2.0
 4      2.2
 5      2.9
 6      3.0
 7      3.2
 8      3.2
 9      3.7
 10     3.9
 11     4.0
 12     4.0
 13     4.1
 14     4.5
 15     4.9
 16     5.1
 17     5.3
 18     5.9
 19     6.0
 20     6.8
 21     7.1
 22     7.9
 23     8.2
 24     8.7
 25     9.0
 26     9.5
 27     9.6
 28    10.3
 29    10.5
 Name: YearsExperience, dtype: float64,
 0      39343
 1      46205
 2      37731
 3      43525
 4      39891
 5      56642
 6      60150
 7      54445
 8      64445
 9      57189
 10     63218
 11     55794
 12     56957
 13     57081
 14     61111
 15     67938
 16     66029
 17     83088
 18     81363
 19     93940
 20     91738
 21     98273
 22    101302
 23    113812
 24    109431
 25    105582
 26    116969
 27    112635
 28    122391
 29    121872
 Name: Salary, dtype: int64)

In [43]:
dependent, independent

(array([[ 1.1, 21. ],
        [ 1.3, 21.5],
        [ 1.5, 21.7],
        [ 2. , 22. ],
        [ 2.2, 22.2],
        [ 2.9, 23. ],
        [ 3. , 23. ],
        [ 3.2, 23.3],
        [ 3.2, 23.3],
        [ 3.7, 23.6],
        [ 3.9, 23.9],
        [ 4. , 24. ],
        [ 4. , 24. ],
        [ 4.1, 24. ],
        [ 4.5, 25. ],
        [ 4.9, 25. ],
        [ 5.1, 26. ],
        [ 5.3, 27. ],
        [ 5.9, 28. ],
        [ 6. , 29. ],
        [ 6.8, 30. ],
        [ 7.1, 30. ],
        [ 7.9, 31. ],
        [ 8.2, 32. ],
        [ 8.7, 33. ],
        [ 9. , 34. ],
        [ 9.5, 35. ],
        [ 9.6, 36. ],
        [10.3, 37. ],
        [10.5, 38. ]]),
 array([ 39343,  46205,  37731,  43525,  39891,  56642,  60150,  54445,
         64445,  57189,  63218,  55794,  56957,  57081,  61111,  67938,
         66029,  83088,  81363,  93940,  91738,  98273, 101302, 113812,
        109431, 105582, 116969, 112635, 122391, 121872]))

In [35]:
# Here split the data into Training & Testing
    
X_train, X_test, y_train, y_test = train_test_split(dependent, independent, test_size=0.3, random_state=0)



In [36]:
## Model design

model = LinearRegression()

model.fit(X_train,y_train)

LinearRegression()

In [41]:
prediction = model.predict(X_test)
prediction


array([21.7, 37. , 24. , 23.9, 35. , 33. , 36. , 24. , 27. ])